/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'hello'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

struct hacker
{
  char *alias;
  char **hacks;
  int hacksCnt;
};

/* 9 */
struct  zoo
{
  int tigers;
  int giraffes;
};

/* 10 */
struct house
{
  int rooms;
  char *adddress;
};

